#!/bin/bash

HIVE_IMAGE_DIR="/hiveserver/image"
HIVE_DIR="/hiveserver/root"
SERVER_CONF="/hiveserver/serv.conf"
HIVE_TFTP="/hiveserver/tftp"
HIVE_CONFDIR="/hiveserver/hive-config"

#Check image and mount it
image_cnt=$(ls $HIVE_IMAGE_DIR/hive*.img -l | wc -l)

if [[ $image_cnt -ne 1 ]]; then
	echo "Error! Image file not found or more than one image file found in $HIVE_IMAGE_DIR"
	exit 1
fi

HIVE_IMAGE=$(ls $HIVE_IMAGE_DIR/hive*.img)
echo $HIVE_IMAGE


[[ ! -d $HIVE_DIR ]] && echo "Create HIVE root directory" && mkdir $HIVE_DIR
cat /proc/mounts | grep -q $HIVE_DIR
if [[ $? -eq 0 ]]; then
	echo "Hive root already mount. Skip."
else
	hive_begin=$(parted $HIVE_IMAGE unit B print | grep ext4 | awk '{print $2}')
	hive_begin=${hive_begin/B/}
	mount -o loop,offset=$hive_begin $HIVE_IMAGE $HIVE_DIR/
	[[ $? -ne 0 ]] && echo "Mount HIVE image failed" && exit 1
fi


## Check conf dir and copy it from image if config not found
[[ ! -d $HIVE_CONFDIR ]] && echo "Create hive-conf directory" && mkdir $HIVE_CONFDIR
if [[ -s $HIVE_CONFDIR/rig.conf ]]; then
	echo "$HIVE_CONFDIR/rig.conf found"
else
	cp -R $HIVE_DIR/hive/etc/hive-config.stub/* $HIVE_CONFDIR/
fi

if [[ ! -f $HIVE_TFTP/vmlinuz ]]; then
	found_kernel=$(ls $HIVE_DIR/boot/vmlinuz*hiveos)
	cp $found_kernel $HIVE_TFTP/vmlinuz
	chmod 744 $HIVE_TFTP/vmlinuz
	found_init=$(ls $HIVE_DIR/boot/initrd*hiveos)
	cp $found_init $HIVE_TFTP/initrd.img
	chmod 744 $HIVE_TFTP/initrd.img
fi

echo "Mount HIVE OS image successfull"
exit 0