#!/bin/bash
#Update image

SERVER_CONF="/hiveserver/serv.conf"
HIVE_ROOT="/hiveserver/root"
HIVE_FAKEROOT="/hiveserver/fakeroot"

[[ ! -f $SERVER_CONF ]] && echo "Error! serv.conf not found. Exit" && exit 1

. $SERVER_CONF

###Check Hive root dir and mount hive root FS
if [[ ! -d $HIVE_ROOT ]];then
	echo "Error! Hive rootFS dir not found. Exit."
	exit 1
fi


echo "$SERVER_IPADDR $SERVER_HOSTNAME" >> $HIVE_FAKEROOT/etc/hosts

mount --bind /proc $HIVE_ROOT/proc
mount --bind /sys $HIVE_ROOT/sys
mount --bind /dev $HIVE_ROOT/dev

cat << EOF | chroot $HIVE_ROOT
/hive/sbin/selfupgrade
EOF


umount $HIVE_ROOT/dev
umount $HIVE_ROOT/proc
umount $HIVE_ROOT/sys

exit 0