#!/bin/bash

/hiveserver/efi/sbin/mount-image
[[ $? -ne 0 ]] && exit 1

/hiveserver/efi/sbin/hive-patch
[[ $? -ne 0 ]] && exit 1

/hiveserver/efi/sbin/mount-fakefs mount
[[ $? -ne 0 ]] && exit 1

exit 0